package de.atomfrede.android.scc.dao;

import java.util.List;
import de.atomfrede.android.scc.dao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table COMPETITION.
 */
public class Competition {

    private Long id;
    private String name;
    private Integer competitionNumber;
    private Integer lastSelectedLapPosition;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient CompetitionDao myDao;

    private List<Lap> lapList;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Competition() {
    }

    public Competition(Long id) {
        this.id = id;
    }

    public Competition(Long id, String name, Integer competitionNumber, Integer lastSelectedLapPosition) {
        this.id = id;
        this.name = name;
        this.competitionNumber = competitionNumber;
        this.lastSelectedLapPosition = lastSelectedLapPosition;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getCompetitionDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getCompetitionNumber() {
        return competitionNumber;
    }

    public void setCompetitionNumber(Integer competitionNumber) {
        this.competitionNumber = competitionNumber;
    }

    public Integer getLastSelectedLapPosition() {
        return lastSelectedLapPosition;
    }

    public void setLastSelectedLapPosition(Integer lastSelectedLapPosition) {
        this.lastSelectedLapPosition = lastSelectedLapPosition;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Lap> getLapList() {
        if (lapList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            LapDao targetDao = daoSession.getLapDao();
            List<Lap> lapListNew = targetDao._queryCompetition_LapList(id);
            synchronized (this) {
                if(lapList == null) {
                    lapList = lapListNew;
                }
            }
        }
        return lapList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetLapList() {
        lapList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
