/*
*	 SCC - The Sprintercup Companion App provides you with the Meldeergbnis right on your smartphone
*    
*    Copyright (C) 2012  Frederik Hahne <atomfrede@gmail.com>
*
*    This program is free software: you can redistribute it and/or modify
*    it under the terms of the GNU General Public License as published by
*    the Free Software Foundation, either version 3 of the License, or
*    (at your option) any later version.
*
*    This program is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*    GNU General Public License for more details.
*
*    You should have received a copy of the GNU General Public License
*    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
package de.atomfrede.android.scc.dao;

import java.util.List;
import de.atomfrede.android.scc.dao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table LAP.
 */
public class Lap implements Comparable<Lap> {

    private Integer lapNumber;
    private Long id;
    private Integer competitionNumber;
    private long competitionId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient LapDao myDao;

    private Competition competition;
    private Long competition__resolvedKey;

    private List<LapEntry> lapEntryList;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Lap() {
    }

    public Lap(Long id) {
        this.id = id;
    }

    public Lap(Integer lapNumber, Long id, Integer competitionNumber, long competitionId) {
        this.lapNumber = lapNumber;
        this.id = id;
        this.competitionNumber = competitionNumber;
        this.competitionId = competitionId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getLapDao() : null;
    }

    public Integer getLapNumber() {
        return lapNumber;
    }

    public void setLapNumber(Integer lapNumber) {
        this.lapNumber = lapNumber;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCompetitionNumber() {
        return competitionNumber;
    }

    public void setCompetitionNumber(Integer competitionNumber) {
        this.competitionNumber = competitionNumber;
    }

    public long getCompetitionId() {
        return competitionId;
    }

    public void setCompetitionId(long competitionId) {
        this.competitionId = competitionId;
    }

    /** To-one relationship, resolved on first access. */
    public Competition getCompetition() {
        if (competition__resolvedKey == null || !competition__resolvedKey.equals(competitionId)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            CompetitionDao targetDao = daoSession.getCompetitionDao();
            competition = targetDao.load(competitionId);
            competition__resolvedKey = competitionId;
        }
        return competition;
    }

    public void setCompetition(Competition competition) {
        if (competition == null) {
            throw new DaoException("To-one property 'competitionId' has not-null constraint; cannot set to-one to null");
        }
        this.competition = competition;
        competitionId = competition.getId();
        competition__resolvedKey = competitionId;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public synchronized List<LapEntry> getLapEntryList() {
        if (lapEntryList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            LapEntryDao targetDao = daoSession.getLapEntryDao();
            lapEntryList = targetDao._queryLap_LapEntryList(id);
        }
        return lapEntryList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetLapEntryList() {
        lapEntryList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    
    @Override
    public int hashCode() {
    	int hash = 1;
    	hash = hash * 17 * competitionNumber.intValue();
    	hash = hash * 31 * lapNumber.intValue();
    	return hash;
    }
    
    public int compareTo(Lap another) {
    	if(this.competitionNumber.equals(another.competitionNumber) && this.lapNumber.equals(another.getLapNumber()))
    		return 0;
    	else
    		return 1;
	}
    // KEEP METHODS END

}
