/*
*	 SCC - The Sprintercup Companion App provides you with the Meldeergbnis right on your smartphone
*    
*    Copyright (C) 2012  Frederik Hahne <atomfrede@gmail.com>
*
*    This program is free software: you can redistribute it and/or modify
*    it under the terms of the GNU General Public License as published by
*    the Free Software Foundation, either version 3 of the License, or
*    (at your option) any later version.
*
*    This program is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*    GNU General Public License for more details.
*
*    You should have received a copy of the GNU General Public License
*    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
package de.atomfrede.android.scc.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.SqlUtils;
import de.greenrobot.dao.Query;
import de.greenrobot.dao.QueryBuilder;

import de.atomfrede.android.scc.dao.LapEntry;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table LAP_ENTRY.
*/
public class LapEntryDao extends AbstractDao<LapEntry, Void> {

    public static final String TABLENAME = "LAP_ENTRY";

    /**
     * Properties of entity LapEntry.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property LapId = new Property(0, long.class, "lapId", false, "LAP_ID");
        public final static Property Firstname = new Property(1, String.class, "firstname", false, "FIRSTNAME");
        public final static Property Lastname = new Property(2, String.class, "lastname", false, "LASTNAME");
        public final static Property Year = new Property(3, String.class, "year", false, "YEAR");
        public final static Property Club = new Property(4, String.class, "club", false, "CLUB");
        public final static Property Time = new Property(5, String.class, "time", false, "TIME");
        public final static Property CompetitionNumber = new Property(6, Integer.class, "competitionNumber", false, "COMPETITION_NUMBER");
        public final static Property LapNumber = new Property(7, Integer.class, "lapNumber", false, "LAP_NUMBER");
        public final static Property Lane = new Property(8, Integer.class, "lane", false, "LANE");
    };

    private DaoSession daoSession;

    private Query<LapEntry> lap_LapEntryListQuery;

    public LapEntryDao(DaoConfig config) {
        super(config);
    }
    
    public LapEntryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'LAP_ENTRY' (" + //
                "'LAP_ID' INTEGER NOT NULL ," + // 0: lapId
                "'FIRSTNAME' TEXT," + // 1: firstname
                "'LASTNAME' TEXT," + // 2: lastname
                "'YEAR' TEXT," + // 3: year
                "'CLUB' TEXT," + // 4: club
                "'TIME' TEXT," + // 5: time
                "'COMPETITION_NUMBER' INTEGER," + // 6: competitionNumber
                "'LAP_NUMBER' INTEGER," + // 7: lapNumber
                "'LANE' INTEGER);"); // 8: lane
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'LAP_ENTRY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, LapEntry entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getLapId());
 
        String firstname = entity.getFirstname();
        if (firstname != null) {
            stmt.bindString(2, firstname);
        }
 
        String lastname = entity.getLastname();
        if (lastname != null) {
            stmt.bindString(3, lastname);
        }
 
        String year = entity.getYear();
        if (year != null) {
            stmt.bindString(4, year);
        }
 
        String club = entity.getClub();
        if (club != null) {
            stmt.bindString(5, club);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(6, time);
        }
 
        Integer competitionNumber = entity.getCompetitionNumber();
        if (competitionNumber != null) {
            stmt.bindLong(7, competitionNumber);
        }
 
        Integer lapNumber = entity.getLapNumber();
        if (lapNumber != null) {
            stmt.bindLong(8, lapNumber);
        }
 
        Integer lane = entity.getLane();
        if (lane != null) {
            stmt.bindLong(9, lane);
        }
    }

    @Override
    protected void attachEntity(LapEntry entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public LapEntry readEntity(Cursor cursor, int offset) {
        LapEntry entity = new LapEntry( //
            cursor.getLong(offset + 0), // lapId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // firstname
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // lastname
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // year
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // club
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // time
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // competitionNumber
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // lapNumber
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8) // lane
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, LapEntry entity, int offset) {
        entity.setLapId(cursor.getLong(offset + 0));
        entity.setFirstname(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLastname(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setYear(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setClub(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCompetitionNumber(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setLapNumber(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setLane(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(LapEntry entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(LapEntry entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "lapEntryList" to-many relationship of Lap. */
    public synchronized List<LapEntry> _queryLap_LapEntryList(long lapId) {
        if (lap_LapEntryListQuery == null) {
            QueryBuilder<LapEntry> queryBuilder = queryBuilder();
            queryBuilder.where(Properties.LapId.eq(lapId));
            queryBuilder.orderRaw("LANE ASC");
            lap_LapEntryListQuery = queryBuilder.build();
        } else {
            lap_LapEntryListQuery.setParameter(0, lapId);
        }
        return lap_LapEntryListQuery.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getLapDao().getAllColumns());
            builder.append(" FROM LAP_ENTRY T");
            builder.append(" LEFT JOIN LAP T0 ON T.'LAP_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected LapEntry loadCurrentDeep(Cursor cursor, boolean lock) {
        LapEntry entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Lap lap = loadCurrentOther(daoSession.getLapDao(), cursor, offset);
         if(lap != null) {
            entity.setLap(lap);
        }

        return entity;    
    }

    public LapEntry loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<LapEntry> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<LapEntry> list = new ArrayList<LapEntry>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<LapEntry> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<LapEntry> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
